#!/bin/sh

set -e

CC=clang
CFLAGS="-Wall -Wextra"
LIBS="-lm"
OUT_DIR="/tmp/nkht-proeu"

if [ "$#" = 0 ]; then
  echo "No input file provided"
  echo "Usage: $0 <input_file>"
  exit 1
fi

src_dir=$(dirname "$1")
filename=$(basename "$1")
filename_base="${filename%.*}"
out_file="$OUT_DIR/$filename_base"

mkdir -p "$OUT_DIR"
$CC $CFLAGS -o "$out_file" "$1" $src_dir/lib/*.c $LIBS
echo "="
$out_file
